# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, and Deploy to GCP

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Build, and Deploy to GCP
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' 

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/project-gcp:latest .

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker to Google Container Registry
      run: |
        cat <<EOL > key.json
        ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        EOL
        gcloud auth activate-service-account --key-file=key.json
        gcloud auth configure-docker

    - name: Tag and Push Docker Image to GCR
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/project-gcp:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-gcp:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-gcp:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy project-gcp \
          --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-gcp:latest \
          --platform=managed \
          --region=southeastasia\
          --allow-unauthenticated